# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdamsNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdamsNews
  pod 'Alamofire', '~> 4.9'
  pod 'SwiftyJSON', '~> 4.0'
end
